language: android
jdk: oraclejdk8
dist: trusty

sudo: false

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.0
    - ANDROID_EMU_API_LEVEL=23
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
    - ANDROID_TAG=google_apis
    - QEMU_AUDIO_DRV=none # Remove audio

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$ANDROID_EMU_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_API_LEVEL
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_EMU_API_LEVEL"
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"


before_script:
  - chmod +x gradlew

  # Start the emulator
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMU_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &



#script:
#  - ./gradlew clean build
#  - ./gradlew test